### ISSUE TITLE
Should a widget be in Domain Layer?

### ISSUE THREAD

**Issue by Chetan-Goyal** [alper-efe-sahin/cubit_login#1]
I feel that this text field widget shouldn't be in domain layer and instead be placed in presentation layer.

https://github.com/alper-efe-sahin/cubit_login/blob/3ebc98dcae1e6b4f672c2bec481d48b9a9baf00e/lib/domain/auth_models/auth_text_field.dart#L3

**Comment by alperefesahin** [comment]
You're right. It escaped me. I have recently fixed it. Thank you.
